name: .NET Core CI

on:
  push:
    branches:
      - main
      - '**/feature/*'
  pull_request:
    branches:
      - main
      - '**/feature/*'

jobs:
  restore-and-build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          - Client/MobileClient/MobileClient.csproj
          - Client/WebClient/WebClient.csproj
          - Server/App/App.csproj
          - UnitTests/Client.UnitTests/MobileClient.Tests/MobileClient.Tests.csproj
          - UnitTests/Backend.UnitTests/Server.UnitTests/Server.UnitTests.csproj
          - UnitTests/Backend.UnitTests/Libraries.UnitTests/Libraries.UnitTests.csproj

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Install dependencies
      - name: Install dependencies
        run:
            dotnet restore ${{ matrix.project }}

      # Build the project
      - name: Build ${{ matrix.project }}
        run: |
          if [[ "${{ matrix.project }}" == "Client/MobileClient/MobileClient.csproj" ]]; then
            dotnet build ${{ matrix.project }} --no-restore --configuration Release -f net8.0-android
          elif [[ "${{ matrix.project }}" == "Client/WebClient/WebClient.csproj" ]]; then
            dotnet build ${{ matrix.project }} --no-restore --configuration Release -f net8.0
          elif [[ "${{ matrix.project }}" == "Server/App/App.csproj" ]]; then
            dotnet build ${{ matrix.project }} --no-restore --configuration Release -f net8.0
          elif [[ "${{ matrix.project }}" == "UnitTests/Client.UnitTests/MobileClient.Tests/MobileClient.Tests.csproj" ]]; then
            dotnet build ${{ matrix.project }} --no-restore --configuration Release -f net8.0
          elif [[ "${{ matrix.project }}" == "UnitTests/Backend.UnitTests/Server.UnitTests/Server.UnitTests.csproj" ]]; then
            dotnet build ${{ matrix.project }} --no-restore --configuration Release -f net8.0
          elif [[ "${{ matrix.project }}" == "UnitTests/Backend.UnitTests/Libraries.UnitTests/Libraries.UnitTests.csproj" ]]; then
            dotnet build ${{ matrix.project }} --no-restore --configuration Release -f net8.0
          fi
      # Run tests
      - name: Run tests
        run: dotnet test ${{ matrix.project }} --no-build --verbosity normal --configuration Release

  # test:
  #   needs: restore-and-build
  #   runs-on: windows-latest

  #   steps:
  #     Checkout the code
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     #Setup .NET Core SDK
  #     - name: Setup .NET Core SDK
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '7.x'

  #     #Run tests
  #     - name: Run tests
  #       run: dotnet test --no-build --verbosity normal --configuration Release
