name: .NET Core CI

on:
  push:
    branches:
      - main
      - '**/feature/*'
  pull_request:
    branches:
      - main
      - '**/feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Install dependencies
      - name: Install dependencies
        run: dotnet workload restore

      # Restire NuGet packages
      - name: NuGet restore
        run: nuget restore ShareSkills.Project.sln

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
