name: .NET Core CI

on:
  push:
    branches:
      - main
      - '**/feature/*'
  pull_request:
    branches:
      - main
      - '**/feature/*'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Install dependencies
      - name: Install dependencies
        run: dotnet workload restore

      # Restire NuGet packages
      - name: NuGet restore
        run: nuget restore ShareSkills.Project.sln

      # Build MobileClient
      - name: Build MobileClient
        run: dotnet build ./Client/MobileClient/MobileClient.csproj --configuration Release

        # Build WebClient
      - name: Build WebClient
        run: dotnet build ./Client/WebClient/WebClient.csproj --configuration Release

        # Build App
      - name: Build App
        run: dotnet build ./Server/App/App.csproj --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
